/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.victorripolles.microservice_client.api;

import com.victorripolles.microservice_client.api.dto.ClientCreateRequestDTO;
import com.victorripolles.microservice_client.api.dto.ClientResponseDTO;
import com.victorripolles.microservice_client.api.dto.ClientUpdateRequestDTO;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Api(value = "Clients", description = "the Clients API")
public interface ClientsApi {

    /**
     * POST /clients : Create a new client
     * Adds a new client to the system
     *
     * @param clientCreateRequestDTO  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @ApiOperation(value = "Create a new client", nickname = "createClient", notes = "Adds a new client to the system", response = ClientResponseDTO.class, tags={ "Clients", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created", response = ClientResponseDTO.class),
        @ApiResponse(code = 400, message = "Bad Request"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @PostMapping(
        value = "/clients",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<ClientResponseDTO> createClient(@ApiParam(value = "" ,required=true )  @Valid @RequestBody ClientCreateRequestDTO clientCreateRequestDTO);


    /**
     * DELETE /clients/{clientId} : Delete a client
     * Removes a client identified by the client ID
     *
     * @param clientId Client Identifier (required)
     * @return No Content (status code 204)
     *         or Bad Request (status code 400)
     *         or Client not found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @ApiOperation(value = "Delete a client", nickname = "deleteClient", notes = "Removes a client identified by the client ID", tags={ "Clients", })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 400, message = "Bad Request"),
        @ApiResponse(code = 404, message = "Client not found"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @DeleteMapping(
        value = "/clients/{clientId}"
    )
    ResponseEntity<Void> deleteClient(@Min(1)@ApiParam(value = "Client Identifier",required=true) @PathVariable("clientId") Integer clientId);


    /**
     * GET /clients/{clientId} : Get client by ID
     * Returns a client identified by the client ID
     *
     * @param clientId Client Identifier (required)
     * @return OK (status code 200)
     *         or Invalid Client ID (status code 400)
     *         or Client not found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @ApiOperation(value = "Get client by ID", nickname = "getClientById", notes = "Returns a client identified by the client ID", response = ClientResponseDTO.class, tags={ "Clients", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ClientResponseDTO.class),
        @ApiResponse(code = 400, message = "Invalid Client ID"),
        @ApiResponse(code = 404, message = "Client not found"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @GetMapping(
        value = "/clients/{clientId}",
        produces = { "application/json" }
    )
    ResponseEntity<ClientResponseDTO> getClientById(@Min(1)@ApiParam(value = "Client Identifier",required=true) @PathVariable("clientId") Integer clientId);


    /**
     * GET /clients : Get list of clients
     * Returns all registered clients
     *
     * @return OK (status code 200)
     *         or No Content (status code 204)
     *         or Internal Server Error (status code 500)
     */
    @ApiOperation(value = "Get list of clients", nickname = "getClients", notes = "Returns all registered clients", response = ClientResponseDTO.class, responseContainer = "List", tags={ "Clients", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ClientResponseDTO.class, responseContainer = "List"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @GetMapping(
        value = "/clients",
        produces = { "application/json" }
    )
    ResponseEntity<List<ClientResponseDTO>> getClients();


    /**
     * PUT /clients/{clientId} : Update client information
     * Updates client data identified by the client ID
     *
     * @param clientId Client Identifier (required)
     * @param clientUpdateRequestDTO  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Client not found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @ApiOperation(value = "Update client information", nickname = "updateClient", notes = "Updates client data identified by the client ID", response = ClientResponseDTO.class, tags={ "Clients", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ClientResponseDTO.class),
        @ApiResponse(code = 400, message = "Bad Request"),
        @ApiResponse(code = 404, message = "Client not found"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @PutMapping(
        value = "/clients/{clientId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<ClientResponseDTO> updateClient(@Min(1)@ApiParam(value = "Client Identifier",required=true) @PathVariable("clientId") Integer clientId,@ApiParam(value = "" ,required=true )  @Valid @RequestBody ClientUpdateRequestDTO clientUpdateRequestDTO);

}
